services:
  postgres:
    image: postgres:15-alpine
    container_name: oase_db
    restart: always
    environment:
      POSTGRES_USER: oasejiwa
      POSTGRES_PASSWORD: sosok_menginspirasi
      POSTGRES_DB: oase_jiwa_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: oase_backend
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    volumes:
      - ./uploads:/app/uploads

    # Tambahkan ini
    env_file:
      - .env

    environment:
      PORT: 3001
      DATABASE_URL: postgresql://oasejiwa:sosok_menginspirasi@postgres:5432/oase_jiwa_db

volumes:
  postgres_data: