version: '3.8'

services:
  # Database PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: oase_db
    restart: always
    environment:
      POSTGRES_USER: oasejiwa
      POSTGRES_PASSWORD: sosok_menginspirasi
      POSTGRES_DB: oase_jiwa_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: oase_db
    restart: always
    ports:
      - "5433:5432"
    depends_on:
      - postgres
    volumes:
      - .:/app
      - ./uploads:/app/uploads
    environment:
      DATABASE_URL: postgresql://oasejiwa:sosok_menginspirasi@localhost:5433/oase_jiwa_db

  # Portainer (UI untuk manajemen Docker)
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/var/data

volumes:
  postgres_data:
  portainer_data: