services:
  postgres:
    image: postgres:15-alpine
    container_name: oase_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-oasejiwa}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-sosok_menginspirasi}
      POSTGRES_DB: ${POSTGRES_DB:-oase_jiwa_db}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: oase_backend
    restart: always
    ports:
      - "${PORT:-3001}:${PORT:-3001}"
    depends_on:
      - postgres
    volumes:
      - ./uploads:/app/uploads

    env_file:
      - .env

    environment:
      PORT: ${PORT:-3001}
      DATABASE_URL: ${DATABASE_URL:-postgresql://${POSTGRES_USER:-oasejiwa}:${POSTGRES_PASSWORD:-sosok_menginspirasi}@postgres:5432/${POSTGRES_DB:-oase_jiwa_db}}

volumes:
  postgres_data: