
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Psychologist` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model Psychologist
 * 
 */
export type PsychologistModel = runtime.Types.Result.DefaultSelection<Prisma.$PsychologistPayload>

export type AggregatePsychologist = {
  _count: PsychologistCountAggregateOutputType | null
  _avg: PsychologistAvgAggregateOutputType | null
  _sum: PsychologistSumAggregateOutputType | null
  _min: PsychologistMinAggregateOutputType | null
  _max: PsychologistMaxAggregateOutputType | null
}

export type PsychologistAvgAggregateOutputType = {
  id: number | null
  userId: number | null
}

export type PsychologistSumAggregateOutputType = {
  id: number | null
  userId: number | null
}

export type PsychologistMinAggregateOutputType = {
  id: number | null
  userId: number | null
  education: string | null
  experience: string | null
  approach: string | null
  specialization: string | null
  photoUrl: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type PsychologistMaxAggregateOutputType = {
  id: number | null
  userId: number | null
  education: string | null
  experience: string | null
  approach: string | null
  specialization: string | null
  photoUrl: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type PsychologistCountAggregateOutputType = {
  id: number
  userId: number
  education: number
  experience: number
  approach: number
  specialization: number
  photoUrl: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type PsychologistAvgAggregateInputType = {
  id?: true
  userId?: true
}

export type PsychologistSumAggregateInputType = {
  id?: true
  userId?: true
}

export type PsychologistMinAggregateInputType = {
  id?: true
  userId?: true
  education?: true
  experience?: true
  approach?: true
  specialization?: true
  photoUrl?: true
  createdAt?: true
  updatedAt?: true
}

export type PsychologistMaxAggregateInputType = {
  id?: true
  userId?: true
  education?: true
  experience?: true
  approach?: true
  specialization?: true
  photoUrl?: true
  createdAt?: true
  updatedAt?: true
}

export type PsychologistCountAggregateInputType = {
  id?: true
  userId?: true
  education?: true
  experience?: true
  approach?: true
  specialization?: true
  photoUrl?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type PsychologistAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Psychologist to aggregate.
   */
  where?: Prisma.PsychologistWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Psychologists to fetch.
   */
  orderBy?: Prisma.PsychologistOrderByWithRelationInput | Prisma.PsychologistOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PsychologistWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Psychologists from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Psychologists.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Psychologists
  **/
  _count?: true | PsychologistCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: PsychologistAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: PsychologistSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PsychologistMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PsychologistMaxAggregateInputType
}

export type GetPsychologistAggregateType<T extends PsychologistAggregateArgs> = {
      [P in keyof T & keyof AggregatePsychologist]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePsychologist[P]>
    : Prisma.GetScalarType<T[P], AggregatePsychologist[P]>
}




export type PsychologistGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PsychologistWhereInput
  orderBy?: Prisma.PsychologistOrderByWithAggregationInput | Prisma.PsychologistOrderByWithAggregationInput[]
  by: Prisma.PsychologistScalarFieldEnum[] | Prisma.PsychologistScalarFieldEnum
  having?: Prisma.PsychologistScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PsychologistCountAggregateInputType | true
  _avg?: PsychologistAvgAggregateInputType
  _sum?: PsychologistSumAggregateInputType
  _min?: PsychologistMinAggregateInputType
  _max?: PsychologistMaxAggregateInputType
}

export type PsychologistGroupByOutputType = {
  id: number
  userId: number
  education: string | null
  experience: string | null
  approach: string | null
  specialization: string | null
  photoUrl: string | null
  createdAt: Date
  updatedAt: Date
  _count: PsychologistCountAggregateOutputType | null
  _avg: PsychologistAvgAggregateOutputType | null
  _sum: PsychologistSumAggregateOutputType | null
  _min: PsychologistMinAggregateOutputType | null
  _max: PsychologistMaxAggregateOutputType | null
}

type GetPsychologistGroupByPayload<T extends PsychologistGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PsychologistGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PsychologistGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PsychologistGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PsychologistGroupByOutputType[P]>
      }
    >
  >



export type PsychologistWhereInput = {
  AND?: Prisma.PsychologistWhereInput | Prisma.PsychologistWhereInput[]
  OR?: Prisma.PsychologistWhereInput[]
  NOT?: Prisma.PsychologistWhereInput | Prisma.PsychologistWhereInput[]
  id?: Prisma.IntFilter<"Psychologist"> | number
  userId?: Prisma.IntFilter<"Psychologist"> | number
  education?: Prisma.StringNullableFilter<"Psychologist"> | string | null
  experience?: Prisma.StringNullableFilter<"Psychologist"> | string | null
  approach?: Prisma.StringNullableFilter<"Psychologist"> | string | null
  specialization?: Prisma.StringNullableFilter<"Psychologist"> | string | null
  photoUrl?: Prisma.StringNullableFilter<"Psychologist"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Psychologist"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Psychologist"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  sessions?: Prisma.SessionListRelationFilter
  notes?: Prisma.SessionNoteListRelationFilter
}

export type PsychologistOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  education?: Prisma.SortOrderInput | Prisma.SortOrder
  experience?: Prisma.SortOrderInput | Prisma.SortOrder
  approach?: Prisma.SortOrderInput | Prisma.SortOrder
  specialization?: Prisma.SortOrderInput | Prisma.SortOrder
  photoUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
  sessions?: Prisma.SessionOrderByRelationAggregateInput
  notes?: Prisma.SessionNoteOrderByRelationAggregateInput
}

export type PsychologistWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  userId?: number
  AND?: Prisma.PsychologistWhereInput | Prisma.PsychologistWhereInput[]
  OR?: Prisma.PsychologistWhereInput[]
  NOT?: Prisma.PsychologistWhereInput | Prisma.PsychologistWhereInput[]
  education?: Prisma.StringNullableFilter<"Psychologist"> | string | null
  experience?: Prisma.StringNullableFilter<"Psychologist"> | string | null
  approach?: Prisma.StringNullableFilter<"Psychologist"> | string | null
  specialization?: Prisma.StringNullableFilter<"Psychologist"> | string | null
  photoUrl?: Prisma.StringNullableFilter<"Psychologist"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Psychologist"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Psychologist"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  sessions?: Prisma.SessionListRelationFilter
  notes?: Prisma.SessionNoteListRelationFilter
}, "id" | "userId">

export type PsychologistOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  education?: Prisma.SortOrderInput | Prisma.SortOrder
  experience?: Prisma.SortOrderInput | Prisma.SortOrder
  approach?: Prisma.SortOrderInput | Prisma.SortOrder
  specialization?: Prisma.SortOrderInput | Prisma.SortOrder
  photoUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.PsychologistCountOrderByAggregateInput
  _avg?: Prisma.PsychologistAvgOrderByAggregateInput
  _max?: Prisma.PsychologistMaxOrderByAggregateInput
  _min?: Prisma.PsychologistMinOrderByAggregateInput
  _sum?: Prisma.PsychologistSumOrderByAggregateInput
}

export type PsychologistScalarWhereWithAggregatesInput = {
  AND?: Prisma.PsychologistScalarWhereWithAggregatesInput | Prisma.PsychologistScalarWhereWithAggregatesInput[]
  OR?: Prisma.PsychologistScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PsychologistScalarWhereWithAggregatesInput | Prisma.PsychologistScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Psychologist"> | number
  userId?: Prisma.IntWithAggregatesFilter<"Psychologist"> | number
  education?: Prisma.StringNullableWithAggregatesFilter<"Psychologist"> | string | null
  experience?: Prisma.StringNullableWithAggregatesFilter<"Psychologist"> | string | null
  approach?: Prisma.StringNullableWithAggregatesFilter<"Psychologist"> | string | null
  specialization?: Prisma.StringNullableWithAggregatesFilter<"Psychologist"> | string | null
  photoUrl?: Prisma.StringNullableWithAggregatesFilter<"Psychologist"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Psychologist"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Psychologist"> | Date | string
}

export type PsychologistCreateInput = {
  education?: string | null
  experience?: string | null
  approach?: string | null
  specialization?: string | null
  photoUrl?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutPsychologistProfileInput
  sessions?: Prisma.SessionCreateNestedManyWithoutPsychologistInput
  notes?: Prisma.SessionNoteCreateNestedManyWithoutPsychologistInput
}

export type PsychologistUncheckedCreateInput = {
  id?: number
  userId: number
  education?: string | null
  experience?: string | null
  approach?: string | null
  specialization?: string | null
  photoUrl?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  sessions?: Prisma.SessionUncheckedCreateNestedManyWithoutPsychologistInput
  notes?: Prisma.SessionNoteUncheckedCreateNestedManyWithoutPsychologistInput
}

export type PsychologistUpdateInput = {
  education?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  experience?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  approach?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  specialization?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  photoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutPsychologistProfileNestedInput
  sessions?: Prisma.SessionUpdateManyWithoutPsychologistNestedInput
  notes?: Prisma.SessionNoteUpdateManyWithoutPsychologistNestedInput
}

export type PsychologistUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  education?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  experience?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  approach?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  specialization?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  photoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  sessions?: Prisma.SessionUncheckedUpdateManyWithoutPsychologistNestedInput
  notes?: Prisma.SessionNoteUncheckedUpdateManyWithoutPsychologistNestedInput
}

export type PsychologistCreateManyInput = {
  id?: number
  userId: number
  education?: string | null
  experience?: string | null
  approach?: string | null
  specialization?: string | null
  photoUrl?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PsychologistUpdateManyMutationInput = {
  education?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  experience?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  approach?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  specialization?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  photoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PsychologistUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  education?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  experience?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  approach?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  specialization?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  photoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PsychologistNullableScalarRelationFilter = {
  is?: Prisma.PsychologistWhereInput | null
  isNot?: Prisma.PsychologistWhereInput | null
}

export type PsychologistCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  education?: Prisma.SortOrder
  experience?: Prisma.SortOrder
  approach?: Prisma.SortOrder
  specialization?: Prisma.SortOrder
  photoUrl?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PsychologistAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
}

export type PsychologistMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  education?: Prisma.SortOrder
  experience?: Prisma.SortOrder
  approach?: Prisma.SortOrder
  specialization?: Prisma.SortOrder
  photoUrl?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PsychologistMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  education?: Prisma.SortOrder
  experience?: Prisma.SortOrder
  approach?: Prisma.SortOrder
  specialization?: Prisma.SortOrder
  photoUrl?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PsychologistSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
}

export type PsychologistScalarRelationFilter = {
  is?: Prisma.PsychologistWhereInput
  isNot?: Prisma.PsychologistWhereInput
}

export type PsychologistCreateNestedOneWithoutUserInput = {
  create?: Prisma.XOR<Prisma.PsychologistCreateWithoutUserInput, Prisma.PsychologistUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.PsychologistCreateOrConnectWithoutUserInput
  connect?: Prisma.PsychologistWhereUniqueInput
}

export type PsychologistUncheckedCreateNestedOneWithoutUserInput = {
  create?: Prisma.XOR<Prisma.PsychologistCreateWithoutUserInput, Prisma.PsychologistUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.PsychologistCreateOrConnectWithoutUserInput
  connect?: Prisma.PsychologistWhereUniqueInput
}

export type PsychologistUpdateOneWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.PsychologistCreateWithoutUserInput, Prisma.PsychologistUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.PsychologistCreateOrConnectWithoutUserInput
  upsert?: Prisma.PsychologistUpsertWithoutUserInput
  disconnect?: Prisma.PsychologistWhereInput | boolean
  delete?: Prisma.PsychologistWhereInput | boolean
  connect?: Prisma.PsychologistWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PsychologistUpdateToOneWithWhereWithoutUserInput, Prisma.PsychologistUpdateWithoutUserInput>, Prisma.PsychologistUncheckedUpdateWithoutUserInput>
}

export type PsychologistUncheckedUpdateOneWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.PsychologistCreateWithoutUserInput, Prisma.PsychologistUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.PsychologistCreateOrConnectWithoutUserInput
  upsert?: Prisma.PsychologistUpsertWithoutUserInput
  disconnect?: Prisma.PsychologistWhereInput | boolean
  delete?: Prisma.PsychologistWhereInput | boolean
  connect?: Prisma.PsychologistWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PsychologistUpdateToOneWithWhereWithoutUserInput, Prisma.PsychologistUpdateWithoutUserInput>, Prisma.PsychologistUncheckedUpdateWithoutUserInput>
}

export type PsychologistCreateNestedOneWithoutSessionsInput = {
  create?: Prisma.XOR<Prisma.PsychologistCreateWithoutSessionsInput, Prisma.PsychologistUncheckedCreateWithoutSessionsInput>
  connectOrCreate?: Prisma.PsychologistCreateOrConnectWithoutSessionsInput
  connect?: Prisma.PsychologistWhereUniqueInput
}

export type PsychologistUpdateOneRequiredWithoutSessionsNestedInput = {
  create?: Prisma.XOR<Prisma.PsychologistCreateWithoutSessionsInput, Prisma.PsychologistUncheckedCreateWithoutSessionsInput>
  connectOrCreate?: Prisma.PsychologistCreateOrConnectWithoutSessionsInput
  upsert?: Prisma.PsychologistUpsertWithoutSessionsInput
  connect?: Prisma.PsychologistWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PsychologistUpdateToOneWithWhereWithoutSessionsInput, Prisma.PsychologistUpdateWithoutSessionsInput>, Prisma.PsychologistUncheckedUpdateWithoutSessionsInput>
}

export type PsychologistCreateNestedOneWithoutNotesInput = {
  create?: Prisma.XOR<Prisma.PsychologistCreateWithoutNotesInput, Prisma.PsychologistUncheckedCreateWithoutNotesInput>
  connectOrCreate?: Prisma.PsychologistCreateOrConnectWithoutNotesInput
  connect?: Prisma.PsychologistWhereUniqueInput
}

export type PsychologistUpdateOneRequiredWithoutNotesNestedInput = {
  create?: Prisma.XOR<Prisma.PsychologistCreateWithoutNotesInput, Prisma.PsychologistUncheckedCreateWithoutNotesInput>
  connectOrCreate?: Prisma.PsychologistCreateOrConnectWithoutNotesInput
  upsert?: Prisma.PsychologistUpsertWithoutNotesInput
  connect?: Prisma.PsychologistWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PsychologistUpdateToOneWithWhereWithoutNotesInput, Prisma.PsychologistUpdateWithoutNotesInput>, Prisma.PsychologistUncheckedUpdateWithoutNotesInput>
}

export type PsychologistCreateWithoutUserInput = {
  education?: string | null
  experience?: string | null
  approach?: string | null
  specialization?: string | null
  photoUrl?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  sessions?: Prisma.SessionCreateNestedManyWithoutPsychologistInput
  notes?: Prisma.SessionNoteCreateNestedManyWithoutPsychologistInput
}

export type PsychologistUncheckedCreateWithoutUserInput = {
  id?: number
  education?: string | null
  experience?: string | null
  approach?: string | null
  specialization?: string | null
  photoUrl?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  sessions?: Prisma.SessionUncheckedCreateNestedManyWithoutPsychologistInput
  notes?: Prisma.SessionNoteUncheckedCreateNestedManyWithoutPsychologistInput
}

export type PsychologistCreateOrConnectWithoutUserInput = {
  where: Prisma.PsychologistWhereUniqueInput
  create: Prisma.XOR<Prisma.PsychologistCreateWithoutUserInput, Prisma.PsychologistUncheckedCreateWithoutUserInput>
}

export type PsychologistUpsertWithoutUserInput = {
  update: Prisma.XOR<Prisma.PsychologistUpdateWithoutUserInput, Prisma.PsychologistUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.PsychologistCreateWithoutUserInput, Prisma.PsychologistUncheckedCreateWithoutUserInput>
  where?: Prisma.PsychologistWhereInput
}

export type PsychologistUpdateToOneWithWhereWithoutUserInput = {
  where?: Prisma.PsychologistWhereInput
  data: Prisma.XOR<Prisma.PsychologistUpdateWithoutUserInput, Prisma.PsychologistUncheckedUpdateWithoutUserInput>
}

export type PsychologistUpdateWithoutUserInput = {
  education?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  experience?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  approach?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  specialization?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  photoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  sessions?: Prisma.SessionUpdateManyWithoutPsychologistNestedInput
  notes?: Prisma.SessionNoteUpdateManyWithoutPsychologistNestedInput
}

export type PsychologistUncheckedUpdateWithoutUserInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  education?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  experience?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  approach?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  specialization?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  photoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  sessions?: Prisma.SessionUncheckedUpdateManyWithoutPsychologistNestedInput
  notes?: Prisma.SessionNoteUncheckedUpdateManyWithoutPsychologistNestedInput
}

export type PsychologistCreateWithoutSessionsInput = {
  education?: string | null
  experience?: string | null
  approach?: string | null
  specialization?: string | null
  photoUrl?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutPsychologistProfileInput
  notes?: Prisma.SessionNoteCreateNestedManyWithoutPsychologistInput
}

export type PsychologistUncheckedCreateWithoutSessionsInput = {
  id?: number
  userId: number
  education?: string | null
  experience?: string | null
  approach?: string | null
  specialization?: string | null
  photoUrl?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  notes?: Prisma.SessionNoteUncheckedCreateNestedManyWithoutPsychologistInput
}

export type PsychologistCreateOrConnectWithoutSessionsInput = {
  where: Prisma.PsychologistWhereUniqueInput
  create: Prisma.XOR<Prisma.PsychologistCreateWithoutSessionsInput, Prisma.PsychologistUncheckedCreateWithoutSessionsInput>
}

export type PsychologistUpsertWithoutSessionsInput = {
  update: Prisma.XOR<Prisma.PsychologistUpdateWithoutSessionsInput, Prisma.PsychologistUncheckedUpdateWithoutSessionsInput>
  create: Prisma.XOR<Prisma.PsychologistCreateWithoutSessionsInput, Prisma.PsychologistUncheckedCreateWithoutSessionsInput>
  where?: Prisma.PsychologistWhereInput
}

export type PsychologistUpdateToOneWithWhereWithoutSessionsInput = {
  where?: Prisma.PsychologistWhereInput
  data: Prisma.XOR<Prisma.PsychologistUpdateWithoutSessionsInput, Prisma.PsychologistUncheckedUpdateWithoutSessionsInput>
}

export type PsychologistUpdateWithoutSessionsInput = {
  education?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  experience?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  approach?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  specialization?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  photoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutPsychologistProfileNestedInput
  notes?: Prisma.SessionNoteUpdateManyWithoutPsychologistNestedInput
}

export type PsychologistUncheckedUpdateWithoutSessionsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  education?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  experience?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  approach?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  specialization?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  photoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  notes?: Prisma.SessionNoteUncheckedUpdateManyWithoutPsychologistNestedInput
}

export type PsychologistCreateWithoutNotesInput = {
  education?: string | null
  experience?: string | null
  approach?: string | null
  specialization?: string | null
  photoUrl?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutPsychologistProfileInput
  sessions?: Prisma.SessionCreateNestedManyWithoutPsychologistInput
}

export type PsychologistUncheckedCreateWithoutNotesInput = {
  id?: number
  userId: number
  education?: string | null
  experience?: string | null
  approach?: string | null
  specialization?: string | null
  photoUrl?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  sessions?: Prisma.SessionUncheckedCreateNestedManyWithoutPsychologistInput
}

export type PsychologistCreateOrConnectWithoutNotesInput = {
  where: Prisma.PsychologistWhereUniqueInput
  create: Prisma.XOR<Prisma.PsychologistCreateWithoutNotesInput, Prisma.PsychologistUncheckedCreateWithoutNotesInput>
}

export type PsychologistUpsertWithoutNotesInput = {
  update: Prisma.XOR<Prisma.PsychologistUpdateWithoutNotesInput, Prisma.PsychologistUncheckedUpdateWithoutNotesInput>
  create: Prisma.XOR<Prisma.PsychologistCreateWithoutNotesInput, Prisma.PsychologistUncheckedCreateWithoutNotesInput>
  where?: Prisma.PsychologistWhereInput
}

export type PsychologistUpdateToOneWithWhereWithoutNotesInput = {
  where?: Prisma.PsychologistWhereInput
  data: Prisma.XOR<Prisma.PsychologistUpdateWithoutNotesInput, Prisma.PsychologistUncheckedUpdateWithoutNotesInput>
}

export type PsychologistUpdateWithoutNotesInput = {
  education?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  experience?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  approach?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  specialization?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  photoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutPsychologistProfileNestedInput
  sessions?: Prisma.SessionUpdateManyWithoutPsychologistNestedInput
}

export type PsychologistUncheckedUpdateWithoutNotesInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  education?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  experience?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  approach?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  specialization?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  photoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  sessions?: Prisma.SessionUncheckedUpdateManyWithoutPsychologistNestedInput
}


/**
 * Count Type PsychologistCountOutputType
 */

export type PsychologistCountOutputType = {
  sessions: number
  notes: number
}

export type PsychologistCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  sessions?: boolean | PsychologistCountOutputTypeCountSessionsArgs
  notes?: boolean | PsychologistCountOutputTypeCountNotesArgs
}

/**
 * PsychologistCountOutputType without action
 */
export type PsychologistCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PsychologistCountOutputType
   */
  select?: Prisma.PsychologistCountOutputTypeSelect<ExtArgs> | null
}

/**
 * PsychologistCountOutputType without action
 */
export type PsychologistCountOutputTypeCountSessionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SessionWhereInput
}

/**
 * PsychologistCountOutputType without action
 */
export type PsychologistCountOutputTypeCountNotesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SessionNoteWhereInput
}


export type PsychologistSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  education?: boolean
  experience?: boolean
  approach?: boolean
  specialization?: boolean
  photoUrl?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  sessions?: boolean | Prisma.Psychologist$sessionsArgs<ExtArgs>
  notes?: boolean | Prisma.Psychologist$notesArgs<ExtArgs>
  _count?: boolean | Prisma.PsychologistCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["psychologist"]>

export type PsychologistSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  education?: boolean
  experience?: boolean
  approach?: boolean
  specialization?: boolean
  photoUrl?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["psychologist"]>

export type PsychologistSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  education?: boolean
  experience?: boolean
  approach?: boolean
  specialization?: boolean
  photoUrl?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["psychologist"]>

export type PsychologistSelectScalar = {
  id?: boolean
  userId?: boolean
  education?: boolean
  experience?: boolean
  approach?: boolean
  specialization?: boolean
  photoUrl?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type PsychologistOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "education" | "experience" | "approach" | "specialization" | "photoUrl" | "createdAt" | "updatedAt", ExtArgs["result"]["psychologist"]>
export type PsychologistInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  sessions?: boolean | Prisma.Psychologist$sessionsArgs<ExtArgs>
  notes?: boolean | Prisma.Psychologist$notesArgs<ExtArgs>
  _count?: boolean | Prisma.PsychologistCountOutputTypeDefaultArgs<ExtArgs>
}
export type PsychologistIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type PsychologistIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $PsychologistPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Psychologist"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
    sessions: Prisma.$SessionPayload<ExtArgs>[]
    notes: Prisma.$SessionNotePayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    userId: number
    education: string | null
    experience: string | null
    approach: string | null
    specialization: string | null
    photoUrl: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["psychologist"]>
  composites: {}
}

export type PsychologistGetPayload<S extends boolean | null | undefined | PsychologistDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PsychologistPayload, S>

export type PsychologistCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PsychologistFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PsychologistCountAggregateInputType | true
  }

export interface PsychologistDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Psychologist'], meta: { name: 'Psychologist' } }
  /**
   * Find zero or one Psychologist that matches the filter.
   * @param {PsychologistFindUniqueArgs} args - Arguments to find a Psychologist
   * @example
   * // Get one Psychologist
   * const psychologist = await prisma.psychologist.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PsychologistFindUniqueArgs>(args: Prisma.SelectSubset<T, PsychologistFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PsychologistClient<runtime.Types.Result.GetResult<Prisma.$PsychologistPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Psychologist that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PsychologistFindUniqueOrThrowArgs} args - Arguments to find a Psychologist
   * @example
   * // Get one Psychologist
   * const psychologist = await prisma.psychologist.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PsychologistFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PsychologistFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PsychologistClient<runtime.Types.Result.GetResult<Prisma.$PsychologistPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Psychologist that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PsychologistFindFirstArgs} args - Arguments to find a Psychologist
   * @example
   * // Get one Psychologist
   * const psychologist = await prisma.psychologist.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PsychologistFindFirstArgs>(args?: Prisma.SelectSubset<T, PsychologistFindFirstArgs<ExtArgs>>): Prisma.Prisma__PsychologistClient<runtime.Types.Result.GetResult<Prisma.$PsychologistPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Psychologist that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PsychologistFindFirstOrThrowArgs} args - Arguments to find a Psychologist
   * @example
   * // Get one Psychologist
   * const psychologist = await prisma.psychologist.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PsychologistFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PsychologistFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PsychologistClient<runtime.Types.Result.GetResult<Prisma.$PsychologistPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Psychologists that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PsychologistFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Psychologists
   * const psychologists = await prisma.psychologist.findMany()
   * 
   * // Get first 10 Psychologists
   * const psychologists = await prisma.psychologist.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const psychologistWithIdOnly = await prisma.psychologist.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends PsychologistFindManyArgs>(args?: Prisma.SelectSubset<T, PsychologistFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PsychologistPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Psychologist.
   * @param {PsychologistCreateArgs} args - Arguments to create a Psychologist.
   * @example
   * // Create one Psychologist
   * const Psychologist = await prisma.psychologist.create({
   *   data: {
   *     // ... data to create a Psychologist
   *   }
   * })
   * 
   */
  create<T extends PsychologistCreateArgs>(args: Prisma.SelectSubset<T, PsychologistCreateArgs<ExtArgs>>): Prisma.Prisma__PsychologistClient<runtime.Types.Result.GetResult<Prisma.$PsychologistPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Psychologists.
   * @param {PsychologistCreateManyArgs} args - Arguments to create many Psychologists.
   * @example
   * // Create many Psychologists
   * const psychologist = await prisma.psychologist.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PsychologistCreateManyArgs>(args?: Prisma.SelectSubset<T, PsychologistCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Psychologists and returns the data saved in the database.
   * @param {PsychologistCreateManyAndReturnArgs} args - Arguments to create many Psychologists.
   * @example
   * // Create many Psychologists
   * const psychologist = await prisma.psychologist.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Psychologists and only return the `id`
   * const psychologistWithIdOnly = await prisma.psychologist.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PsychologistCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PsychologistCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PsychologistPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Psychologist.
   * @param {PsychologistDeleteArgs} args - Arguments to delete one Psychologist.
   * @example
   * // Delete one Psychologist
   * const Psychologist = await prisma.psychologist.delete({
   *   where: {
   *     // ... filter to delete one Psychologist
   *   }
   * })
   * 
   */
  delete<T extends PsychologistDeleteArgs>(args: Prisma.SelectSubset<T, PsychologistDeleteArgs<ExtArgs>>): Prisma.Prisma__PsychologistClient<runtime.Types.Result.GetResult<Prisma.$PsychologistPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Psychologist.
   * @param {PsychologistUpdateArgs} args - Arguments to update one Psychologist.
   * @example
   * // Update one Psychologist
   * const psychologist = await prisma.psychologist.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PsychologistUpdateArgs>(args: Prisma.SelectSubset<T, PsychologistUpdateArgs<ExtArgs>>): Prisma.Prisma__PsychologistClient<runtime.Types.Result.GetResult<Prisma.$PsychologistPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Psychologists.
   * @param {PsychologistDeleteManyArgs} args - Arguments to filter Psychologists to delete.
   * @example
   * // Delete a few Psychologists
   * const { count } = await prisma.psychologist.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PsychologistDeleteManyArgs>(args?: Prisma.SelectSubset<T, PsychologistDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Psychologists.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PsychologistUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Psychologists
   * const psychologist = await prisma.psychologist.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PsychologistUpdateManyArgs>(args: Prisma.SelectSubset<T, PsychologistUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Psychologists and returns the data updated in the database.
   * @param {PsychologistUpdateManyAndReturnArgs} args - Arguments to update many Psychologists.
   * @example
   * // Update many Psychologists
   * const psychologist = await prisma.psychologist.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Psychologists and only return the `id`
   * const psychologistWithIdOnly = await prisma.psychologist.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PsychologistUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PsychologistUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PsychologistPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Psychologist.
   * @param {PsychologistUpsertArgs} args - Arguments to update or create a Psychologist.
   * @example
   * // Update or create a Psychologist
   * const psychologist = await prisma.psychologist.upsert({
   *   create: {
   *     // ... data to create a Psychologist
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Psychologist we want to update
   *   }
   * })
   */
  upsert<T extends PsychologistUpsertArgs>(args: Prisma.SelectSubset<T, PsychologistUpsertArgs<ExtArgs>>): Prisma.Prisma__PsychologistClient<runtime.Types.Result.GetResult<Prisma.$PsychologistPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Psychologists.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PsychologistCountArgs} args - Arguments to filter Psychologists to count.
   * @example
   * // Count the number of Psychologists
   * const count = await prisma.psychologist.count({
   *   where: {
   *     // ... the filter for the Psychologists we want to count
   *   }
   * })
  **/
  count<T extends PsychologistCountArgs>(
    args?: Prisma.Subset<T, PsychologistCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PsychologistCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Psychologist.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PsychologistAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PsychologistAggregateArgs>(args: Prisma.Subset<T, PsychologistAggregateArgs>): Prisma.PrismaPromise<GetPsychologistAggregateType<T>>

  /**
   * Group by Psychologist.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PsychologistGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PsychologistGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PsychologistGroupByArgs['orderBy'] }
      : { orderBy?: PsychologistGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PsychologistGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPsychologistGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Psychologist model
 */
readonly fields: PsychologistFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Psychologist.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PsychologistClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  sessions<T extends Prisma.Psychologist$sessionsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Psychologist$sessionsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SessionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  notes<T extends Prisma.Psychologist$notesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Psychologist$notesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SessionNotePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Psychologist model
 */
export interface PsychologistFieldRefs {
  readonly id: Prisma.FieldRef<"Psychologist", 'Int'>
  readonly userId: Prisma.FieldRef<"Psychologist", 'Int'>
  readonly education: Prisma.FieldRef<"Psychologist", 'String'>
  readonly experience: Prisma.FieldRef<"Psychologist", 'String'>
  readonly approach: Prisma.FieldRef<"Psychologist", 'String'>
  readonly specialization: Prisma.FieldRef<"Psychologist", 'String'>
  readonly photoUrl: Prisma.FieldRef<"Psychologist", 'String'>
  readonly createdAt: Prisma.FieldRef<"Psychologist", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Psychologist", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Psychologist findUnique
 */
export type PsychologistFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Psychologist
   */
  select?: Prisma.PsychologistSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Psychologist
   */
  omit?: Prisma.PsychologistOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PsychologistInclude<ExtArgs> | null
  /**
   * Filter, which Psychologist to fetch.
   */
  where: Prisma.PsychologistWhereUniqueInput
}

/**
 * Psychologist findUniqueOrThrow
 */
export type PsychologistFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Psychologist
   */
  select?: Prisma.PsychologistSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Psychologist
   */
  omit?: Prisma.PsychologistOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PsychologistInclude<ExtArgs> | null
  /**
   * Filter, which Psychologist to fetch.
   */
  where: Prisma.PsychologistWhereUniqueInput
}

/**
 * Psychologist findFirst
 */
export type PsychologistFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Psychologist
   */
  select?: Prisma.PsychologistSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Psychologist
   */
  omit?: Prisma.PsychologistOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PsychologistInclude<ExtArgs> | null
  /**
   * Filter, which Psychologist to fetch.
   */
  where?: Prisma.PsychologistWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Psychologists to fetch.
   */
  orderBy?: Prisma.PsychologistOrderByWithRelationInput | Prisma.PsychologistOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Psychologists.
   */
  cursor?: Prisma.PsychologistWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Psychologists from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Psychologists.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Psychologists.
   */
  distinct?: Prisma.PsychologistScalarFieldEnum | Prisma.PsychologistScalarFieldEnum[]
}

/**
 * Psychologist findFirstOrThrow
 */
export type PsychologistFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Psychologist
   */
  select?: Prisma.PsychologistSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Psychologist
   */
  omit?: Prisma.PsychologistOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PsychologistInclude<ExtArgs> | null
  /**
   * Filter, which Psychologist to fetch.
   */
  where?: Prisma.PsychologistWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Psychologists to fetch.
   */
  orderBy?: Prisma.PsychologistOrderByWithRelationInput | Prisma.PsychologistOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Psychologists.
   */
  cursor?: Prisma.PsychologistWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Psychologists from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Psychologists.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Psychologists.
   */
  distinct?: Prisma.PsychologistScalarFieldEnum | Prisma.PsychologistScalarFieldEnum[]
}

/**
 * Psychologist findMany
 */
export type PsychologistFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Psychologist
   */
  select?: Prisma.PsychologistSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Psychologist
   */
  omit?: Prisma.PsychologistOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PsychologistInclude<ExtArgs> | null
  /**
   * Filter, which Psychologists to fetch.
   */
  where?: Prisma.PsychologistWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Psychologists to fetch.
   */
  orderBy?: Prisma.PsychologistOrderByWithRelationInput | Prisma.PsychologistOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Psychologists.
   */
  cursor?: Prisma.PsychologistWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Psychologists from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Psychologists.
   */
  skip?: number
  distinct?: Prisma.PsychologistScalarFieldEnum | Prisma.PsychologistScalarFieldEnum[]
}

/**
 * Psychologist create
 */
export type PsychologistCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Psychologist
   */
  select?: Prisma.PsychologistSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Psychologist
   */
  omit?: Prisma.PsychologistOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PsychologistInclude<ExtArgs> | null
  /**
   * The data needed to create a Psychologist.
   */
  data: Prisma.XOR<Prisma.PsychologistCreateInput, Prisma.PsychologistUncheckedCreateInput>
}

/**
 * Psychologist createMany
 */
export type PsychologistCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Psychologists.
   */
  data: Prisma.PsychologistCreateManyInput | Prisma.PsychologistCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Psychologist createManyAndReturn
 */
export type PsychologistCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Psychologist
   */
  select?: Prisma.PsychologistSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Psychologist
   */
  omit?: Prisma.PsychologistOmit<ExtArgs> | null
  /**
   * The data used to create many Psychologists.
   */
  data: Prisma.PsychologistCreateManyInput | Prisma.PsychologistCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PsychologistIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Psychologist update
 */
export type PsychologistUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Psychologist
   */
  select?: Prisma.PsychologistSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Psychologist
   */
  omit?: Prisma.PsychologistOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PsychologistInclude<ExtArgs> | null
  /**
   * The data needed to update a Psychologist.
   */
  data: Prisma.XOR<Prisma.PsychologistUpdateInput, Prisma.PsychologistUncheckedUpdateInput>
  /**
   * Choose, which Psychologist to update.
   */
  where: Prisma.PsychologistWhereUniqueInput
}

/**
 * Psychologist updateMany
 */
export type PsychologistUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Psychologists.
   */
  data: Prisma.XOR<Prisma.PsychologistUpdateManyMutationInput, Prisma.PsychologistUncheckedUpdateManyInput>
  /**
   * Filter which Psychologists to update
   */
  where?: Prisma.PsychologistWhereInput
  /**
   * Limit how many Psychologists to update.
   */
  limit?: number
}

/**
 * Psychologist updateManyAndReturn
 */
export type PsychologistUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Psychologist
   */
  select?: Prisma.PsychologistSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Psychologist
   */
  omit?: Prisma.PsychologistOmit<ExtArgs> | null
  /**
   * The data used to update Psychologists.
   */
  data: Prisma.XOR<Prisma.PsychologistUpdateManyMutationInput, Prisma.PsychologistUncheckedUpdateManyInput>
  /**
   * Filter which Psychologists to update
   */
  where?: Prisma.PsychologistWhereInput
  /**
   * Limit how many Psychologists to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PsychologistIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Psychologist upsert
 */
export type PsychologistUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Psychologist
   */
  select?: Prisma.PsychologistSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Psychologist
   */
  omit?: Prisma.PsychologistOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PsychologistInclude<ExtArgs> | null
  /**
   * The filter to search for the Psychologist to update in case it exists.
   */
  where: Prisma.PsychologistWhereUniqueInput
  /**
   * In case the Psychologist found by the `where` argument doesn't exist, create a new Psychologist with this data.
   */
  create: Prisma.XOR<Prisma.PsychologistCreateInput, Prisma.PsychologistUncheckedCreateInput>
  /**
   * In case the Psychologist was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PsychologistUpdateInput, Prisma.PsychologistUncheckedUpdateInput>
}

/**
 * Psychologist delete
 */
export type PsychologistDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Psychologist
   */
  select?: Prisma.PsychologistSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Psychologist
   */
  omit?: Prisma.PsychologistOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PsychologistInclude<ExtArgs> | null
  /**
   * Filter which Psychologist to delete.
   */
  where: Prisma.PsychologistWhereUniqueInput
}

/**
 * Psychologist deleteMany
 */
export type PsychologistDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Psychologists to delete
   */
  where?: Prisma.PsychologistWhereInput
  /**
   * Limit how many Psychologists to delete.
   */
  limit?: number
}

/**
 * Psychologist.sessions
 */
export type Psychologist$sessionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Session
   */
  select?: Prisma.SessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Session
   */
  omit?: Prisma.SessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SessionInclude<ExtArgs> | null
  where?: Prisma.SessionWhereInput
  orderBy?: Prisma.SessionOrderByWithRelationInput | Prisma.SessionOrderByWithRelationInput[]
  cursor?: Prisma.SessionWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.SessionScalarFieldEnum | Prisma.SessionScalarFieldEnum[]
}

/**
 * Psychologist.notes
 */
export type Psychologist$notesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SessionNote
   */
  select?: Prisma.SessionNoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SessionNote
   */
  omit?: Prisma.SessionNoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SessionNoteInclude<ExtArgs> | null
  where?: Prisma.SessionNoteWhereInput
  orderBy?: Prisma.SessionNoteOrderByWithRelationInput | Prisma.SessionNoteOrderByWithRelationInput[]
  cursor?: Prisma.SessionNoteWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.SessionNoteScalarFieldEnum | Prisma.SessionNoteScalarFieldEnum[]
}

/**
 * Psychologist without action
 */
export type PsychologistDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Psychologist
   */
  select?: Prisma.PsychologistSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Psychologist
   */
  omit?: Prisma.PsychologistOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PsychologistInclude<ExtArgs> | null
}
