
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `SessionNote` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model SessionNote
 * 
 */
export type SessionNoteModel = runtime.Types.Result.DefaultSelection<Prisma.$SessionNotePayload>

export type AggregateSessionNote = {
  _count: SessionNoteCountAggregateOutputType | null
  _avg: SessionNoteAvgAggregateOutputType | null
  _sum: SessionNoteSumAggregateOutputType | null
  _min: SessionNoteMinAggregateOutputType | null
  _max: SessionNoteMaxAggregateOutputType | null
}

export type SessionNoteAvgAggregateOutputType = {
  id: number | null
  sessionId: number | null
  psychologistId: number | null
  patientId: number | null
}

export type SessionNoteSumAggregateOutputType = {
  id: number | null
  sessionId: number | null
  psychologistId: number | null
  patientId: number | null
}

export type SessionNoteMinAggregateOutputType = {
  id: number | null
  sessionId: number | null
  psychologistId: number | null
  patientId: number | null
  subjective: string | null
  objective: string | null
  assessment: string | null
  plan: string | null
  riskLevel: $Enums.RiskLevel | null
  createdAt: Date | null
  updatedAt: Date | null
  deletedAt: Date | null
}

export type SessionNoteMaxAggregateOutputType = {
  id: number | null
  sessionId: number | null
  psychologistId: number | null
  patientId: number | null
  subjective: string | null
  objective: string | null
  assessment: string | null
  plan: string | null
  riskLevel: $Enums.RiskLevel | null
  createdAt: Date | null
  updatedAt: Date | null
  deletedAt: Date | null
}

export type SessionNoteCountAggregateOutputType = {
  id: number
  sessionId: number
  psychologistId: number
  patientId: number
  subjective: number
  objective: number
  assessment: number
  plan: number
  riskLevel: number
  createdAt: number
  updatedAt: number
  deletedAt: number
  _all: number
}


export type SessionNoteAvgAggregateInputType = {
  id?: true
  sessionId?: true
  psychologistId?: true
  patientId?: true
}

export type SessionNoteSumAggregateInputType = {
  id?: true
  sessionId?: true
  psychologistId?: true
  patientId?: true
}

export type SessionNoteMinAggregateInputType = {
  id?: true
  sessionId?: true
  psychologistId?: true
  patientId?: true
  subjective?: true
  objective?: true
  assessment?: true
  plan?: true
  riskLevel?: true
  createdAt?: true
  updatedAt?: true
  deletedAt?: true
}

export type SessionNoteMaxAggregateInputType = {
  id?: true
  sessionId?: true
  psychologistId?: true
  patientId?: true
  subjective?: true
  objective?: true
  assessment?: true
  plan?: true
  riskLevel?: true
  createdAt?: true
  updatedAt?: true
  deletedAt?: true
}

export type SessionNoteCountAggregateInputType = {
  id?: true
  sessionId?: true
  psychologistId?: true
  patientId?: true
  subjective?: true
  objective?: true
  assessment?: true
  plan?: true
  riskLevel?: true
  createdAt?: true
  updatedAt?: true
  deletedAt?: true
  _all?: true
}

export type SessionNoteAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SessionNote to aggregate.
   */
  where?: Prisma.SessionNoteWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SessionNotes to fetch.
   */
  orderBy?: Prisma.SessionNoteOrderByWithRelationInput | Prisma.SessionNoteOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.SessionNoteWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SessionNotes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SessionNotes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned SessionNotes
  **/
  _count?: true | SessionNoteCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: SessionNoteAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: SessionNoteSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: SessionNoteMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: SessionNoteMaxAggregateInputType
}

export type GetSessionNoteAggregateType<T extends SessionNoteAggregateArgs> = {
      [P in keyof T & keyof AggregateSessionNote]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSessionNote[P]>
    : Prisma.GetScalarType<T[P], AggregateSessionNote[P]>
}




export type SessionNoteGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SessionNoteWhereInput
  orderBy?: Prisma.SessionNoteOrderByWithAggregationInput | Prisma.SessionNoteOrderByWithAggregationInput[]
  by: Prisma.SessionNoteScalarFieldEnum[] | Prisma.SessionNoteScalarFieldEnum
  having?: Prisma.SessionNoteScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: SessionNoteCountAggregateInputType | true
  _avg?: SessionNoteAvgAggregateInputType
  _sum?: SessionNoteSumAggregateInputType
  _min?: SessionNoteMinAggregateInputType
  _max?: SessionNoteMaxAggregateInputType
}

export type SessionNoteGroupByOutputType = {
  id: number
  sessionId: number
  psychologistId: number
  patientId: number
  subjective: string | null
  objective: string | null
  assessment: string | null
  plan: string | null
  riskLevel: $Enums.RiskLevel
  createdAt: Date
  updatedAt: Date
  deletedAt: Date | null
  _count: SessionNoteCountAggregateOutputType | null
  _avg: SessionNoteAvgAggregateOutputType | null
  _sum: SessionNoteSumAggregateOutputType | null
  _min: SessionNoteMinAggregateOutputType | null
  _max: SessionNoteMaxAggregateOutputType | null
}

type GetSessionNoteGroupByPayload<T extends SessionNoteGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<SessionNoteGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof SessionNoteGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], SessionNoteGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], SessionNoteGroupByOutputType[P]>
      }
    >
  >



export type SessionNoteWhereInput = {
  AND?: Prisma.SessionNoteWhereInput | Prisma.SessionNoteWhereInput[]
  OR?: Prisma.SessionNoteWhereInput[]
  NOT?: Prisma.SessionNoteWhereInput | Prisma.SessionNoteWhereInput[]
  id?: Prisma.IntFilter<"SessionNote"> | number
  sessionId?: Prisma.IntFilter<"SessionNote"> | number
  psychologistId?: Prisma.IntFilter<"SessionNote"> | number
  patientId?: Prisma.IntFilter<"SessionNote"> | number
  subjective?: Prisma.StringNullableFilter<"SessionNote"> | string | null
  objective?: Prisma.StringNullableFilter<"SessionNote"> | string | null
  assessment?: Prisma.StringNullableFilter<"SessionNote"> | string | null
  plan?: Prisma.StringNullableFilter<"SessionNote"> | string | null
  riskLevel?: Prisma.EnumRiskLevelFilter<"SessionNote"> | $Enums.RiskLevel
  createdAt?: Prisma.DateTimeFilter<"SessionNote"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"SessionNote"> | Date | string
  deletedAt?: Prisma.DateTimeNullableFilter<"SessionNote"> | Date | string | null
  session?: Prisma.XOR<Prisma.SessionScalarRelationFilter, Prisma.SessionWhereInput>
  psychologist?: Prisma.XOR<Prisma.PsychologistScalarRelationFilter, Prisma.PsychologistWhereInput>
  patient?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type SessionNoteOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  sessionId?: Prisma.SortOrder
  psychologistId?: Prisma.SortOrder
  patientId?: Prisma.SortOrder
  subjective?: Prisma.SortOrderInput | Prisma.SortOrder
  objective?: Prisma.SortOrderInput | Prisma.SortOrder
  assessment?: Prisma.SortOrderInput | Prisma.SortOrder
  plan?: Prisma.SortOrderInput | Prisma.SortOrder
  riskLevel?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  session?: Prisma.SessionOrderByWithRelationInput
  psychologist?: Prisma.PsychologistOrderByWithRelationInput
  patient?: Prisma.UserOrderByWithRelationInput
}

export type SessionNoteWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  sessionId?: number
  AND?: Prisma.SessionNoteWhereInput | Prisma.SessionNoteWhereInput[]
  OR?: Prisma.SessionNoteWhereInput[]
  NOT?: Prisma.SessionNoteWhereInput | Prisma.SessionNoteWhereInput[]
  psychologistId?: Prisma.IntFilter<"SessionNote"> | number
  patientId?: Prisma.IntFilter<"SessionNote"> | number
  subjective?: Prisma.StringNullableFilter<"SessionNote"> | string | null
  objective?: Prisma.StringNullableFilter<"SessionNote"> | string | null
  assessment?: Prisma.StringNullableFilter<"SessionNote"> | string | null
  plan?: Prisma.StringNullableFilter<"SessionNote"> | string | null
  riskLevel?: Prisma.EnumRiskLevelFilter<"SessionNote"> | $Enums.RiskLevel
  createdAt?: Prisma.DateTimeFilter<"SessionNote"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"SessionNote"> | Date | string
  deletedAt?: Prisma.DateTimeNullableFilter<"SessionNote"> | Date | string | null
  session?: Prisma.XOR<Prisma.SessionScalarRelationFilter, Prisma.SessionWhereInput>
  psychologist?: Prisma.XOR<Prisma.PsychologistScalarRelationFilter, Prisma.PsychologistWhereInput>
  patient?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id" | "sessionId">

export type SessionNoteOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  sessionId?: Prisma.SortOrder
  psychologistId?: Prisma.SortOrder
  patientId?: Prisma.SortOrder
  subjective?: Prisma.SortOrderInput | Prisma.SortOrder
  objective?: Prisma.SortOrderInput | Prisma.SortOrder
  assessment?: Prisma.SortOrderInput | Prisma.SortOrder
  plan?: Prisma.SortOrderInput | Prisma.SortOrder
  riskLevel?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.SessionNoteCountOrderByAggregateInput
  _avg?: Prisma.SessionNoteAvgOrderByAggregateInput
  _max?: Prisma.SessionNoteMaxOrderByAggregateInput
  _min?: Prisma.SessionNoteMinOrderByAggregateInput
  _sum?: Prisma.SessionNoteSumOrderByAggregateInput
}

export type SessionNoteScalarWhereWithAggregatesInput = {
  AND?: Prisma.SessionNoteScalarWhereWithAggregatesInput | Prisma.SessionNoteScalarWhereWithAggregatesInput[]
  OR?: Prisma.SessionNoteScalarWhereWithAggregatesInput[]
  NOT?: Prisma.SessionNoteScalarWhereWithAggregatesInput | Prisma.SessionNoteScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"SessionNote"> | number
  sessionId?: Prisma.IntWithAggregatesFilter<"SessionNote"> | number
  psychologistId?: Prisma.IntWithAggregatesFilter<"SessionNote"> | number
  patientId?: Prisma.IntWithAggregatesFilter<"SessionNote"> | number
  subjective?: Prisma.StringNullableWithAggregatesFilter<"SessionNote"> | string | null
  objective?: Prisma.StringNullableWithAggregatesFilter<"SessionNote"> | string | null
  assessment?: Prisma.StringNullableWithAggregatesFilter<"SessionNote"> | string | null
  plan?: Prisma.StringNullableWithAggregatesFilter<"SessionNote"> | string | null
  riskLevel?: Prisma.EnumRiskLevelWithAggregatesFilter<"SessionNote"> | $Enums.RiskLevel
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"SessionNote"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"SessionNote"> | Date | string
  deletedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"SessionNote"> | Date | string | null
}

export type SessionNoteCreateInput = {
  subjective?: string | null
  objective?: string | null
  assessment?: string | null
  plan?: string | null
  riskLevel?: $Enums.RiskLevel
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  session: Prisma.SessionCreateNestedOneWithoutNoteInput
  psychologist: Prisma.PsychologistCreateNestedOneWithoutNotesInput
  patient: Prisma.UserCreateNestedOneWithoutPatientNotesInput
}

export type SessionNoteUncheckedCreateInput = {
  id?: number
  sessionId: number
  psychologistId: number
  patientId: number
  subjective?: string | null
  objective?: string | null
  assessment?: string | null
  plan?: string | null
  riskLevel?: $Enums.RiskLevel
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
}

export type SessionNoteUpdateInput = {
  subjective?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  objective?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  assessment?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  plan?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  riskLevel?: Prisma.EnumRiskLevelFieldUpdateOperationsInput | $Enums.RiskLevel
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  session?: Prisma.SessionUpdateOneRequiredWithoutNoteNestedInput
  psychologist?: Prisma.PsychologistUpdateOneRequiredWithoutNotesNestedInput
  patient?: Prisma.UserUpdateOneRequiredWithoutPatientNotesNestedInput
}

export type SessionNoteUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  sessionId?: Prisma.IntFieldUpdateOperationsInput | number
  psychologistId?: Prisma.IntFieldUpdateOperationsInput | number
  patientId?: Prisma.IntFieldUpdateOperationsInput | number
  subjective?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  objective?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  assessment?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  plan?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  riskLevel?: Prisma.EnumRiskLevelFieldUpdateOperationsInput | $Enums.RiskLevel
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type SessionNoteCreateManyInput = {
  id?: number
  sessionId: number
  psychologistId: number
  patientId: number
  subjective?: string | null
  objective?: string | null
  assessment?: string | null
  plan?: string | null
  riskLevel?: $Enums.RiskLevel
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
}

export type SessionNoteUpdateManyMutationInput = {
  subjective?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  objective?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  assessment?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  plan?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  riskLevel?: Prisma.EnumRiskLevelFieldUpdateOperationsInput | $Enums.RiskLevel
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type SessionNoteUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  sessionId?: Prisma.IntFieldUpdateOperationsInput | number
  psychologistId?: Prisma.IntFieldUpdateOperationsInput | number
  patientId?: Prisma.IntFieldUpdateOperationsInput | number
  subjective?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  objective?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  assessment?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  plan?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  riskLevel?: Prisma.EnumRiskLevelFieldUpdateOperationsInput | $Enums.RiskLevel
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type SessionNoteListRelationFilter = {
  every?: Prisma.SessionNoteWhereInput
  some?: Prisma.SessionNoteWhereInput
  none?: Prisma.SessionNoteWhereInput
}

export type SessionNoteOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type SessionNoteNullableScalarRelationFilter = {
  is?: Prisma.SessionNoteWhereInput | null
  isNot?: Prisma.SessionNoteWhereInput | null
}

export type SessionNoteCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  sessionId?: Prisma.SortOrder
  psychologistId?: Prisma.SortOrder
  patientId?: Prisma.SortOrder
  subjective?: Prisma.SortOrder
  objective?: Prisma.SortOrder
  assessment?: Prisma.SortOrder
  plan?: Prisma.SortOrder
  riskLevel?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
}

export type SessionNoteAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  sessionId?: Prisma.SortOrder
  psychologistId?: Prisma.SortOrder
  patientId?: Prisma.SortOrder
}

export type SessionNoteMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  sessionId?: Prisma.SortOrder
  psychologistId?: Prisma.SortOrder
  patientId?: Prisma.SortOrder
  subjective?: Prisma.SortOrder
  objective?: Prisma.SortOrder
  assessment?: Prisma.SortOrder
  plan?: Prisma.SortOrder
  riskLevel?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
}

export type SessionNoteMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  sessionId?: Prisma.SortOrder
  psychologistId?: Prisma.SortOrder
  patientId?: Prisma.SortOrder
  subjective?: Prisma.SortOrder
  objective?: Prisma.SortOrder
  assessment?: Prisma.SortOrder
  plan?: Prisma.SortOrder
  riskLevel?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
}

export type SessionNoteSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  sessionId?: Prisma.SortOrder
  psychologistId?: Prisma.SortOrder
  patientId?: Prisma.SortOrder
}

export type SessionNoteCreateNestedManyWithoutPatientInput = {
  create?: Prisma.XOR<Prisma.SessionNoteCreateWithoutPatientInput, Prisma.SessionNoteUncheckedCreateWithoutPatientInput> | Prisma.SessionNoteCreateWithoutPatientInput[] | Prisma.SessionNoteUncheckedCreateWithoutPatientInput[]
  connectOrCreate?: Prisma.SessionNoteCreateOrConnectWithoutPatientInput | Prisma.SessionNoteCreateOrConnectWithoutPatientInput[]
  createMany?: Prisma.SessionNoteCreateManyPatientInputEnvelope
  connect?: Prisma.SessionNoteWhereUniqueInput | Prisma.SessionNoteWhereUniqueInput[]
}

export type SessionNoteUncheckedCreateNestedManyWithoutPatientInput = {
  create?: Prisma.XOR<Prisma.SessionNoteCreateWithoutPatientInput, Prisma.SessionNoteUncheckedCreateWithoutPatientInput> | Prisma.SessionNoteCreateWithoutPatientInput[] | Prisma.SessionNoteUncheckedCreateWithoutPatientInput[]
  connectOrCreate?: Prisma.SessionNoteCreateOrConnectWithoutPatientInput | Prisma.SessionNoteCreateOrConnectWithoutPatientInput[]
  createMany?: Prisma.SessionNoteCreateManyPatientInputEnvelope
  connect?: Prisma.SessionNoteWhereUniqueInput | Prisma.SessionNoteWhereUniqueInput[]
}

export type SessionNoteUpdateManyWithoutPatientNestedInput = {
  create?: Prisma.XOR<Prisma.SessionNoteCreateWithoutPatientInput, Prisma.SessionNoteUncheckedCreateWithoutPatientInput> | Prisma.SessionNoteCreateWithoutPatientInput[] | Prisma.SessionNoteUncheckedCreateWithoutPatientInput[]
  connectOrCreate?: Prisma.SessionNoteCreateOrConnectWithoutPatientInput | Prisma.SessionNoteCreateOrConnectWithoutPatientInput[]
  upsert?: Prisma.SessionNoteUpsertWithWhereUniqueWithoutPatientInput | Prisma.SessionNoteUpsertWithWhereUniqueWithoutPatientInput[]
  createMany?: Prisma.SessionNoteCreateManyPatientInputEnvelope
  set?: Prisma.SessionNoteWhereUniqueInput | Prisma.SessionNoteWhereUniqueInput[]
  disconnect?: Prisma.SessionNoteWhereUniqueInput | Prisma.SessionNoteWhereUniqueInput[]
  delete?: Prisma.SessionNoteWhereUniqueInput | Prisma.SessionNoteWhereUniqueInput[]
  connect?: Prisma.SessionNoteWhereUniqueInput | Prisma.SessionNoteWhereUniqueInput[]
  update?: Prisma.SessionNoteUpdateWithWhereUniqueWithoutPatientInput | Prisma.SessionNoteUpdateWithWhereUniqueWithoutPatientInput[]
  updateMany?: Prisma.SessionNoteUpdateManyWithWhereWithoutPatientInput | Prisma.SessionNoteUpdateManyWithWhereWithoutPatientInput[]
  deleteMany?: Prisma.SessionNoteScalarWhereInput | Prisma.SessionNoteScalarWhereInput[]
}

export type SessionNoteUncheckedUpdateManyWithoutPatientNestedInput = {
  create?: Prisma.XOR<Prisma.SessionNoteCreateWithoutPatientInput, Prisma.SessionNoteUncheckedCreateWithoutPatientInput> | Prisma.SessionNoteCreateWithoutPatientInput[] | Prisma.SessionNoteUncheckedCreateWithoutPatientInput[]
  connectOrCreate?: Prisma.SessionNoteCreateOrConnectWithoutPatientInput | Prisma.SessionNoteCreateOrConnectWithoutPatientInput[]
  upsert?: Prisma.SessionNoteUpsertWithWhereUniqueWithoutPatientInput | Prisma.SessionNoteUpsertWithWhereUniqueWithoutPatientInput[]
  createMany?: Prisma.SessionNoteCreateManyPatientInputEnvelope
  set?: Prisma.SessionNoteWhereUniqueInput | Prisma.SessionNoteWhereUniqueInput[]
  disconnect?: Prisma.SessionNoteWhereUniqueInput | Prisma.SessionNoteWhereUniqueInput[]
  delete?: Prisma.SessionNoteWhereUniqueInput | Prisma.SessionNoteWhereUniqueInput[]
  connect?: Prisma.SessionNoteWhereUniqueInput | Prisma.SessionNoteWhereUniqueInput[]
  update?: Prisma.SessionNoteUpdateWithWhereUniqueWithoutPatientInput | Prisma.SessionNoteUpdateWithWhereUniqueWithoutPatientInput[]
  updateMany?: Prisma.SessionNoteUpdateManyWithWhereWithoutPatientInput | Prisma.SessionNoteUpdateManyWithWhereWithoutPatientInput[]
  deleteMany?: Prisma.SessionNoteScalarWhereInput | Prisma.SessionNoteScalarWhereInput[]
}

export type SessionNoteCreateNestedManyWithoutPsychologistInput = {
  create?: Prisma.XOR<Prisma.SessionNoteCreateWithoutPsychologistInput, Prisma.SessionNoteUncheckedCreateWithoutPsychologistInput> | Prisma.SessionNoteCreateWithoutPsychologistInput[] | Prisma.SessionNoteUncheckedCreateWithoutPsychologistInput[]
  connectOrCreate?: Prisma.SessionNoteCreateOrConnectWithoutPsychologistInput | Prisma.SessionNoteCreateOrConnectWithoutPsychologistInput[]
  createMany?: Prisma.SessionNoteCreateManyPsychologistInputEnvelope
  connect?: Prisma.SessionNoteWhereUniqueInput | Prisma.SessionNoteWhereUniqueInput[]
}

export type SessionNoteUncheckedCreateNestedManyWithoutPsychologistInput = {
  create?: Prisma.XOR<Prisma.SessionNoteCreateWithoutPsychologistInput, Prisma.SessionNoteUncheckedCreateWithoutPsychologistInput> | Prisma.SessionNoteCreateWithoutPsychologistInput[] | Prisma.SessionNoteUncheckedCreateWithoutPsychologistInput[]
  connectOrCreate?: Prisma.SessionNoteCreateOrConnectWithoutPsychologistInput | Prisma.SessionNoteCreateOrConnectWithoutPsychologistInput[]
  createMany?: Prisma.SessionNoteCreateManyPsychologistInputEnvelope
  connect?: Prisma.SessionNoteWhereUniqueInput | Prisma.SessionNoteWhereUniqueInput[]
}

export type SessionNoteUpdateManyWithoutPsychologistNestedInput = {
  create?: Prisma.XOR<Prisma.SessionNoteCreateWithoutPsychologistInput, Prisma.SessionNoteUncheckedCreateWithoutPsychologistInput> | Prisma.SessionNoteCreateWithoutPsychologistInput[] | Prisma.SessionNoteUncheckedCreateWithoutPsychologistInput[]
  connectOrCreate?: Prisma.SessionNoteCreateOrConnectWithoutPsychologistInput | Prisma.SessionNoteCreateOrConnectWithoutPsychologistInput[]
  upsert?: Prisma.SessionNoteUpsertWithWhereUniqueWithoutPsychologistInput | Prisma.SessionNoteUpsertWithWhereUniqueWithoutPsychologistInput[]
  createMany?: Prisma.SessionNoteCreateManyPsychologistInputEnvelope
  set?: Prisma.SessionNoteWhereUniqueInput | Prisma.SessionNoteWhereUniqueInput[]
  disconnect?: Prisma.SessionNoteWhereUniqueInput | Prisma.SessionNoteWhereUniqueInput[]
  delete?: Prisma.SessionNoteWhereUniqueInput | Prisma.SessionNoteWhereUniqueInput[]
  connect?: Prisma.SessionNoteWhereUniqueInput | Prisma.SessionNoteWhereUniqueInput[]
  update?: Prisma.SessionNoteUpdateWithWhereUniqueWithoutPsychologistInput | Prisma.SessionNoteUpdateWithWhereUniqueWithoutPsychologistInput[]
  updateMany?: Prisma.SessionNoteUpdateManyWithWhereWithoutPsychologistInput | Prisma.SessionNoteUpdateManyWithWhereWithoutPsychologistInput[]
  deleteMany?: Prisma.SessionNoteScalarWhereInput | Prisma.SessionNoteScalarWhereInput[]
}

export type SessionNoteUncheckedUpdateManyWithoutPsychologistNestedInput = {
  create?: Prisma.XOR<Prisma.SessionNoteCreateWithoutPsychologistInput, Prisma.SessionNoteUncheckedCreateWithoutPsychologistInput> | Prisma.SessionNoteCreateWithoutPsychologistInput[] | Prisma.SessionNoteUncheckedCreateWithoutPsychologistInput[]
  connectOrCreate?: Prisma.SessionNoteCreateOrConnectWithoutPsychologistInput | Prisma.SessionNoteCreateOrConnectWithoutPsychologistInput[]
  upsert?: Prisma.SessionNoteUpsertWithWhereUniqueWithoutPsychologistInput | Prisma.SessionNoteUpsertWithWhereUniqueWithoutPsychologistInput[]
  createMany?: Prisma.SessionNoteCreateManyPsychologistInputEnvelope
  set?: Prisma.SessionNoteWhereUniqueInput | Prisma.SessionNoteWhereUniqueInput[]
  disconnect?: Prisma.SessionNoteWhereUniqueInput | Prisma.SessionNoteWhereUniqueInput[]
  delete?: Prisma.SessionNoteWhereUniqueInput | Prisma.SessionNoteWhereUniqueInput[]
  connect?: Prisma.SessionNoteWhereUniqueInput | Prisma.SessionNoteWhereUniqueInput[]
  update?: Prisma.SessionNoteUpdateWithWhereUniqueWithoutPsychologistInput | Prisma.SessionNoteUpdateWithWhereUniqueWithoutPsychologistInput[]
  updateMany?: Prisma.SessionNoteUpdateManyWithWhereWithoutPsychologistInput | Prisma.SessionNoteUpdateManyWithWhereWithoutPsychologistInput[]
  deleteMany?: Prisma.SessionNoteScalarWhereInput | Prisma.SessionNoteScalarWhereInput[]
}

export type SessionNoteCreateNestedOneWithoutSessionInput = {
  create?: Prisma.XOR<Prisma.SessionNoteCreateWithoutSessionInput, Prisma.SessionNoteUncheckedCreateWithoutSessionInput>
  connectOrCreate?: Prisma.SessionNoteCreateOrConnectWithoutSessionInput
  connect?: Prisma.SessionNoteWhereUniqueInput
}

export type SessionNoteUncheckedCreateNestedOneWithoutSessionInput = {
  create?: Prisma.XOR<Prisma.SessionNoteCreateWithoutSessionInput, Prisma.SessionNoteUncheckedCreateWithoutSessionInput>
  connectOrCreate?: Prisma.SessionNoteCreateOrConnectWithoutSessionInput
  connect?: Prisma.SessionNoteWhereUniqueInput
}

export type SessionNoteUpdateOneWithoutSessionNestedInput = {
  create?: Prisma.XOR<Prisma.SessionNoteCreateWithoutSessionInput, Prisma.SessionNoteUncheckedCreateWithoutSessionInput>
  connectOrCreate?: Prisma.SessionNoteCreateOrConnectWithoutSessionInput
  upsert?: Prisma.SessionNoteUpsertWithoutSessionInput
  disconnect?: Prisma.SessionNoteWhereInput | boolean
  delete?: Prisma.SessionNoteWhereInput | boolean
  connect?: Prisma.SessionNoteWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.SessionNoteUpdateToOneWithWhereWithoutSessionInput, Prisma.SessionNoteUpdateWithoutSessionInput>, Prisma.SessionNoteUncheckedUpdateWithoutSessionInput>
}

export type SessionNoteUncheckedUpdateOneWithoutSessionNestedInput = {
  create?: Prisma.XOR<Prisma.SessionNoteCreateWithoutSessionInput, Prisma.SessionNoteUncheckedCreateWithoutSessionInput>
  connectOrCreate?: Prisma.SessionNoteCreateOrConnectWithoutSessionInput
  upsert?: Prisma.SessionNoteUpsertWithoutSessionInput
  disconnect?: Prisma.SessionNoteWhereInput | boolean
  delete?: Prisma.SessionNoteWhereInput | boolean
  connect?: Prisma.SessionNoteWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.SessionNoteUpdateToOneWithWhereWithoutSessionInput, Prisma.SessionNoteUpdateWithoutSessionInput>, Prisma.SessionNoteUncheckedUpdateWithoutSessionInput>
}

export type EnumRiskLevelFieldUpdateOperationsInput = {
  set?: $Enums.RiskLevel
}

export type SessionNoteCreateWithoutPatientInput = {
  subjective?: string | null
  objective?: string | null
  assessment?: string | null
  plan?: string | null
  riskLevel?: $Enums.RiskLevel
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  session: Prisma.SessionCreateNestedOneWithoutNoteInput
  psychologist: Prisma.PsychologistCreateNestedOneWithoutNotesInput
}

export type SessionNoteUncheckedCreateWithoutPatientInput = {
  id?: number
  sessionId: number
  psychologistId: number
  subjective?: string | null
  objective?: string | null
  assessment?: string | null
  plan?: string | null
  riskLevel?: $Enums.RiskLevel
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
}

export type SessionNoteCreateOrConnectWithoutPatientInput = {
  where: Prisma.SessionNoteWhereUniqueInput
  create: Prisma.XOR<Prisma.SessionNoteCreateWithoutPatientInput, Prisma.SessionNoteUncheckedCreateWithoutPatientInput>
}

export type SessionNoteCreateManyPatientInputEnvelope = {
  data: Prisma.SessionNoteCreateManyPatientInput | Prisma.SessionNoteCreateManyPatientInput[]
  skipDuplicates?: boolean
}

export type SessionNoteUpsertWithWhereUniqueWithoutPatientInput = {
  where: Prisma.SessionNoteWhereUniqueInput
  update: Prisma.XOR<Prisma.SessionNoteUpdateWithoutPatientInput, Prisma.SessionNoteUncheckedUpdateWithoutPatientInput>
  create: Prisma.XOR<Prisma.SessionNoteCreateWithoutPatientInput, Prisma.SessionNoteUncheckedCreateWithoutPatientInput>
}

export type SessionNoteUpdateWithWhereUniqueWithoutPatientInput = {
  where: Prisma.SessionNoteWhereUniqueInput
  data: Prisma.XOR<Prisma.SessionNoteUpdateWithoutPatientInput, Prisma.SessionNoteUncheckedUpdateWithoutPatientInput>
}

export type SessionNoteUpdateManyWithWhereWithoutPatientInput = {
  where: Prisma.SessionNoteScalarWhereInput
  data: Prisma.XOR<Prisma.SessionNoteUpdateManyMutationInput, Prisma.SessionNoteUncheckedUpdateManyWithoutPatientInput>
}

export type SessionNoteScalarWhereInput = {
  AND?: Prisma.SessionNoteScalarWhereInput | Prisma.SessionNoteScalarWhereInput[]
  OR?: Prisma.SessionNoteScalarWhereInput[]
  NOT?: Prisma.SessionNoteScalarWhereInput | Prisma.SessionNoteScalarWhereInput[]
  id?: Prisma.IntFilter<"SessionNote"> | number
  sessionId?: Prisma.IntFilter<"SessionNote"> | number
  psychologistId?: Prisma.IntFilter<"SessionNote"> | number
  patientId?: Prisma.IntFilter<"SessionNote"> | number
  subjective?: Prisma.StringNullableFilter<"SessionNote"> | string | null
  objective?: Prisma.StringNullableFilter<"SessionNote"> | string | null
  assessment?: Prisma.StringNullableFilter<"SessionNote"> | string | null
  plan?: Prisma.StringNullableFilter<"SessionNote"> | string | null
  riskLevel?: Prisma.EnumRiskLevelFilter<"SessionNote"> | $Enums.RiskLevel
  createdAt?: Prisma.DateTimeFilter<"SessionNote"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"SessionNote"> | Date | string
  deletedAt?: Prisma.DateTimeNullableFilter<"SessionNote"> | Date | string | null
}

export type SessionNoteCreateWithoutPsychologistInput = {
  subjective?: string | null
  objective?: string | null
  assessment?: string | null
  plan?: string | null
  riskLevel?: $Enums.RiskLevel
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  session: Prisma.SessionCreateNestedOneWithoutNoteInput
  patient: Prisma.UserCreateNestedOneWithoutPatientNotesInput
}

export type SessionNoteUncheckedCreateWithoutPsychologistInput = {
  id?: number
  sessionId: number
  patientId: number
  subjective?: string | null
  objective?: string | null
  assessment?: string | null
  plan?: string | null
  riskLevel?: $Enums.RiskLevel
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
}

export type SessionNoteCreateOrConnectWithoutPsychologistInput = {
  where: Prisma.SessionNoteWhereUniqueInput
  create: Prisma.XOR<Prisma.SessionNoteCreateWithoutPsychologistInput, Prisma.SessionNoteUncheckedCreateWithoutPsychologistInput>
}

export type SessionNoteCreateManyPsychologistInputEnvelope = {
  data: Prisma.SessionNoteCreateManyPsychologistInput | Prisma.SessionNoteCreateManyPsychologistInput[]
  skipDuplicates?: boolean
}

export type SessionNoteUpsertWithWhereUniqueWithoutPsychologistInput = {
  where: Prisma.SessionNoteWhereUniqueInput
  update: Prisma.XOR<Prisma.SessionNoteUpdateWithoutPsychologistInput, Prisma.SessionNoteUncheckedUpdateWithoutPsychologistInput>
  create: Prisma.XOR<Prisma.SessionNoteCreateWithoutPsychologistInput, Prisma.SessionNoteUncheckedCreateWithoutPsychologistInput>
}

export type SessionNoteUpdateWithWhereUniqueWithoutPsychologistInput = {
  where: Prisma.SessionNoteWhereUniqueInput
  data: Prisma.XOR<Prisma.SessionNoteUpdateWithoutPsychologistInput, Prisma.SessionNoteUncheckedUpdateWithoutPsychologistInput>
}

export type SessionNoteUpdateManyWithWhereWithoutPsychologistInput = {
  where: Prisma.SessionNoteScalarWhereInput
  data: Prisma.XOR<Prisma.SessionNoteUpdateManyMutationInput, Prisma.SessionNoteUncheckedUpdateManyWithoutPsychologistInput>
}

export type SessionNoteCreateWithoutSessionInput = {
  subjective?: string | null
  objective?: string | null
  assessment?: string | null
  plan?: string | null
  riskLevel?: $Enums.RiskLevel
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  psychologist: Prisma.PsychologistCreateNestedOneWithoutNotesInput
  patient: Prisma.UserCreateNestedOneWithoutPatientNotesInput
}

export type SessionNoteUncheckedCreateWithoutSessionInput = {
  id?: number
  psychologistId: number
  patientId: number
  subjective?: string | null
  objective?: string | null
  assessment?: string | null
  plan?: string | null
  riskLevel?: $Enums.RiskLevel
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
}

export type SessionNoteCreateOrConnectWithoutSessionInput = {
  where: Prisma.SessionNoteWhereUniqueInput
  create: Prisma.XOR<Prisma.SessionNoteCreateWithoutSessionInput, Prisma.SessionNoteUncheckedCreateWithoutSessionInput>
}

export type SessionNoteUpsertWithoutSessionInput = {
  update: Prisma.XOR<Prisma.SessionNoteUpdateWithoutSessionInput, Prisma.SessionNoteUncheckedUpdateWithoutSessionInput>
  create: Prisma.XOR<Prisma.SessionNoteCreateWithoutSessionInput, Prisma.SessionNoteUncheckedCreateWithoutSessionInput>
  where?: Prisma.SessionNoteWhereInput
}

export type SessionNoteUpdateToOneWithWhereWithoutSessionInput = {
  where?: Prisma.SessionNoteWhereInput
  data: Prisma.XOR<Prisma.SessionNoteUpdateWithoutSessionInput, Prisma.SessionNoteUncheckedUpdateWithoutSessionInput>
}

export type SessionNoteUpdateWithoutSessionInput = {
  subjective?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  objective?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  assessment?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  plan?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  riskLevel?: Prisma.EnumRiskLevelFieldUpdateOperationsInput | $Enums.RiskLevel
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  psychologist?: Prisma.PsychologistUpdateOneRequiredWithoutNotesNestedInput
  patient?: Prisma.UserUpdateOneRequiredWithoutPatientNotesNestedInput
}

export type SessionNoteUncheckedUpdateWithoutSessionInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  psychologistId?: Prisma.IntFieldUpdateOperationsInput | number
  patientId?: Prisma.IntFieldUpdateOperationsInput | number
  subjective?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  objective?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  assessment?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  plan?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  riskLevel?: Prisma.EnumRiskLevelFieldUpdateOperationsInput | $Enums.RiskLevel
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type SessionNoteCreateManyPatientInput = {
  id?: number
  sessionId: number
  psychologistId: number
  subjective?: string | null
  objective?: string | null
  assessment?: string | null
  plan?: string | null
  riskLevel?: $Enums.RiskLevel
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
}

export type SessionNoteUpdateWithoutPatientInput = {
  subjective?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  objective?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  assessment?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  plan?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  riskLevel?: Prisma.EnumRiskLevelFieldUpdateOperationsInput | $Enums.RiskLevel
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  session?: Prisma.SessionUpdateOneRequiredWithoutNoteNestedInput
  psychologist?: Prisma.PsychologistUpdateOneRequiredWithoutNotesNestedInput
}

export type SessionNoteUncheckedUpdateWithoutPatientInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  sessionId?: Prisma.IntFieldUpdateOperationsInput | number
  psychologistId?: Prisma.IntFieldUpdateOperationsInput | number
  subjective?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  objective?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  assessment?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  plan?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  riskLevel?: Prisma.EnumRiskLevelFieldUpdateOperationsInput | $Enums.RiskLevel
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type SessionNoteUncheckedUpdateManyWithoutPatientInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  sessionId?: Prisma.IntFieldUpdateOperationsInput | number
  psychologistId?: Prisma.IntFieldUpdateOperationsInput | number
  subjective?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  objective?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  assessment?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  plan?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  riskLevel?: Prisma.EnumRiskLevelFieldUpdateOperationsInput | $Enums.RiskLevel
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type SessionNoteCreateManyPsychologistInput = {
  id?: number
  sessionId: number
  patientId: number
  subjective?: string | null
  objective?: string | null
  assessment?: string | null
  plan?: string | null
  riskLevel?: $Enums.RiskLevel
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
}

export type SessionNoteUpdateWithoutPsychologistInput = {
  subjective?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  objective?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  assessment?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  plan?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  riskLevel?: Prisma.EnumRiskLevelFieldUpdateOperationsInput | $Enums.RiskLevel
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  session?: Prisma.SessionUpdateOneRequiredWithoutNoteNestedInput
  patient?: Prisma.UserUpdateOneRequiredWithoutPatientNotesNestedInput
}

export type SessionNoteUncheckedUpdateWithoutPsychologistInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  sessionId?: Prisma.IntFieldUpdateOperationsInput | number
  patientId?: Prisma.IntFieldUpdateOperationsInput | number
  subjective?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  objective?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  assessment?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  plan?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  riskLevel?: Prisma.EnumRiskLevelFieldUpdateOperationsInput | $Enums.RiskLevel
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type SessionNoteUncheckedUpdateManyWithoutPsychologistInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  sessionId?: Prisma.IntFieldUpdateOperationsInput | number
  patientId?: Prisma.IntFieldUpdateOperationsInput | number
  subjective?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  objective?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  assessment?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  plan?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  riskLevel?: Prisma.EnumRiskLevelFieldUpdateOperationsInput | $Enums.RiskLevel
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}



export type SessionNoteSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  sessionId?: boolean
  psychologistId?: boolean
  patientId?: boolean
  subjective?: boolean
  objective?: boolean
  assessment?: boolean
  plan?: boolean
  riskLevel?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
  session?: boolean | Prisma.SessionDefaultArgs<ExtArgs>
  psychologist?: boolean | Prisma.PsychologistDefaultArgs<ExtArgs>
  patient?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["sessionNote"]>

export type SessionNoteSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  sessionId?: boolean
  psychologistId?: boolean
  patientId?: boolean
  subjective?: boolean
  objective?: boolean
  assessment?: boolean
  plan?: boolean
  riskLevel?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
  session?: boolean | Prisma.SessionDefaultArgs<ExtArgs>
  psychologist?: boolean | Prisma.PsychologistDefaultArgs<ExtArgs>
  patient?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["sessionNote"]>

export type SessionNoteSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  sessionId?: boolean
  psychologistId?: boolean
  patientId?: boolean
  subjective?: boolean
  objective?: boolean
  assessment?: boolean
  plan?: boolean
  riskLevel?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
  session?: boolean | Prisma.SessionDefaultArgs<ExtArgs>
  psychologist?: boolean | Prisma.PsychologistDefaultArgs<ExtArgs>
  patient?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["sessionNote"]>

export type SessionNoteSelectScalar = {
  id?: boolean
  sessionId?: boolean
  psychologistId?: boolean
  patientId?: boolean
  subjective?: boolean
  objective?: boolean
  assessment?: boolean
  plan?: boolean
  riskLevel?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
}

export type SessionNoteOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "sessionId" | "psychologistId" | "patientId" | "subjective" | "objective" | "assessment" | "plan" | "riskLevel" | "createdAt" | "updatedAt" | "deletedAt", ExtArgs["result"]["sessionNote"]>
export type SessionNoteInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  session?: boolean | Prisma.SessionDefaultArgs<ExtArgs>
  psychologist?: boolean | Prisma.PsychologistDefaultArgs<ExtArgs>
  patient?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type SessionNoteIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  session?: boolean | Prisma.SessionDefaultArgs<ExtArgs>
  psychologist?: boolean | Prisma.PsychologistDefaultArgs<ExtArgs>
  patient?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type SessionNoteIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  session?: boolean | Prisma.SessionDefaultArgs<ExtArgs>
  psychologist?: boolean | Prisma.PsychologistDefaultArgs<ExtArgs>
  patient?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $SessionNotePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "SessionNote"
  objects: {
    session: Prisma.$SessionPayload<ExtArgs>
    psychologist: Prisma.$PsychologistPayload<ExtArgs>
    patient: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    sessionId: number
    psychologistId: number
    patientId: number
    subjective: string | null
    objective: string | null
    assessment: string | null
    plan: string | null
    riskLevel: $Enums.RiskLevel
    createdAt: Date
    updatedAt: Date
    deletedAt: Date | null
  }, ExtArgs["result"]["sessionNote"]>
  composites: {}
}

export type SessionNoteGetPayload<S extends boolean | null | undefined | SessionNoteDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$SessionNotePayload, S>

export type SessionNoteCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<SessionNoteFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: SessionNoteCountAggregateInputType | true
  }

export interface SessionNoteDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['SessionNote'], meta: { name: 'SessionNote' } }
  /**
   * Find zero or one SessionNote that matches the filter.
   * @param {SessionNoteFindUniqueArgs} args - Arguments to find a SessionNote
   * @example
   * // Get one SessionNote
   * const sessionNote = await prisma.sessionNote.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends SessionNoteFindUniqueArgs>(args: Prisma.SelectSubset<T, SessionNoteFindUniqueArgs<ExtArgs>>): Prisma.Prisma__SessionNoteClient<runtime.Types.Result.GetResult<Prisma.$SessionNotePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one SessionNote that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {SessionNoteFindUniqueOrThrowArgs} args - Arguments to find a SessionNote
   * @example
   * // Get one SessionNote
   * const sessionNote = await prisma.sessionNote.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends SessionNoteFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, SessionNoteFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__SessionNoteClient<runtime.Types.Result.GetResult<Prisma.$SessionNotePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SessionNote that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SessionNoteFindFirstArgs} args - Arguments to find a SessionNote
   * @example
   * // Get one SessionNote
   * const sessionNote = await prisma.sessionNote.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends SessionNoteFindFirstArgs>(args?: Prisma.SelectSubset<T, SessionNoteFindFirstArgs<ExtArgs>>): Prisma.Prisma__SessionNoteClient<runtime.Types.Result.GetResult<Prisma.$SessionNotePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SessionNote that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SessionNoteFindFirstOrThrowArgs} args - Arguments to find a SessionNote
   * @example
   * // Get one SessionNote
   * const sessionNote = await prisma.sessionNote.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends SessionNoteFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, SessionNoteFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__SessionNoteClient<runtime.Types.Result.GetResult<Prisma.$SessionNotePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more SessionNotes that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SessionNoteFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all SessionNotes
   * const sessionNotes = await prisma.sessionNote.findMany()
   * 
   * // Get first 10 SessionNotes
   * const sessionNotes = await prisma.sessionNote.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const sessionNoteWithIdOnly = await prisma.sessionNote.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends SessionNoteFindManyArgs>(args?: Prisma.SelectSubset<T, SessionNoteFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SessionNotePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a SessionNote.
   * @param {SessionNoteCreateArgs} args - Arguments to create a SessionNote.
   * @example
   * // Create one SessionNote
   * const SessionNote = await prisma.sessionNote.create({
   *   data: {
   *     // ... data to create a SessionNote
   *   }
   * })
   * 
   */
  create<T extends SessionNoteCreateArgs>(args: Prisma.SelectSubset<T, SessionNoteCreateArgs<ExtArgs>>): Prisma.Prisma__SessionNoteClient<runtime.Types.Result.GetResult<Prisma.$SessionNotePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many SessionNotes.
   * @param {SessionNoteCreateManyArgs} args - Arguments to create many SessionNotes.
   * @example
   * // Create many SessionNotes
   * const sessionNote = await prisma.sessionNote.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends SessionNoteCreateManyArgs>(args?: Prisma.SelectSubset<T, SessionNoteCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many SessionNotes and returns the data saved in the database.
   * @param {SessionNoteCreateManyAndReturnArgs} args - Arguments to create many SessionNotes.
   * @example
   * // Create many SessionNotes
   * const sessionNote = await prisma.sessionNote.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many SessionNotes and only return the `id`
   * const sessionNoteWithIdOnly = await prisma.sessionNote.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends SessionNoteCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, SessionNoteCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SessionNotePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a SessionNote.
   * @param {SessionNoteDeleteArgs} args - Arguments to delete one SessionNote.
   * @example
   * // Delete one SessionNote
   * const SessionNote = await prisma.sessionNote.delete({
   *   where: {
   *     // ... filter to delete one SessionNote
   *   }
   * })
   * 
   */
  delete<T extends SessionNoteDeleteArgs>(args: Prisma.SelectSubset<T, SessionNoteDeleteArgs<ExtArgs>>): Prisma.Prisma__SessionNoteClient<runtime.Types.Result.GetResult<Prisma.$SessionNotePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one SessionNote.
   * @param {SessionNoteUpdateArgs} args - Arguments to update one SessionNote.
   * @example
   * // Update one SessionNote
   * const sessionNote = await prisma.sessionNote.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends SessionNoteUpdateArgs>(args: Prisma.SelectSubset<T, SessionNoteUpdateArgs<ExtArgs>>): Prisma.Prisma__SessionNoteClient<runtime.Types.Result.GetResult<Prisma.$SessionNotePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more SessionNotes.
   * @param {SessionNoteDeleteManyArgs} args - Arguments to filter SessionNotes to delete.
   * @example
   * // Delete a few SessionNotes
   * const { count } = await prisma.sessionNote.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends SessionNoteDeleteManyArgs>(args?: Prisma.SelectSubset<T, SessionNoteDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SessionNotes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SessionNoteUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many SessionNotes
   * const sessionNote = await prisma.sessionNote.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends SessionNoteUpdateManyArgs>(args: Prisma.SelectSubset<T, SessionNoteUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SessionNotes and returns the data updated in the database.
   * @param {SessionNoteUpdateManyAndReturnArgs} args - Arguments to update many SessionNotes.
   * @example
   * // Update many SessionNotes
   * const sessionNote = await prisma.sessionNote.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more SessionNotes and only return the `id`
   * const sessionNoteWithIdOnly = await prisma.sessionNote.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends SessionNoteUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, SessionNoteUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SessionNotePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one SessionNote.
   * @param {SessionNoteUpsertArgs} args - Arguments to update or create a SessionNote.
   * @example
   * // Update or create a SessionNote
   * const sessionNote = await prisma.sessionNote.upsert({
   *   create: {
   *     // ... data to create a SessionNote
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the SessionNote we want to update
   *   }
   * })
   */
  upsert<T extends SessionNoteUpsertArgs>(args: Prisma.SelectSubset<T, SessionNoteUpsertArgs<ExtArgs>>): Prisma.Prisma__SessionNoteClient<runtime.Types.Result.GetResult<Prisma.$SessionNotePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of SessionNotes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SessionNoteCountArgs} args - Arguments to filter SessionNotes to count.
   * @example
   * // Count the number of SessionNotes
   * const count = await prisma.sessionNote.count({
   *   where: {
   *     // ... the filter for the SessionNotes we want to count
   *   }
   * })
  **/
  count<T extends SessionNoteCountArgs>(
    args?: Prisma.Subset<T, SessionNoteCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], SessionNoteCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a SessionNote.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SessionNoteAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends SessionNoteAggregateArgs>(args: Prisma.Subset<T, SessionNoteAggregateArgs>): Prisma.PrismaPromise<GetSessionNoteAggregateType<T>>

  /**
   * Group by SessionNote.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SessionNoteGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends SessionNoteGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: SessionNoteGroupByArgs['orderBy'] }
      : { orderBy?: SessionNoteGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, SessionNoteGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetSessionNoteGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the SessionNote model
 */
readonly fields: SessionNoteFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for SessionNote.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__SessionNoteClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  session<T extends Prisma.SessionDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.SessionDefaultArgs<ExtArgs>>): Prisma.Prisma__SessionClient<runtime.Types.Result.GetResult<Prisma.$SessionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  psychologist<T extends Prisma.PsychologistDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.PsychologistDefaultArgs<ExtArgs>>): Prisma.Prisma__PsychologistClient<runtime.Types.Result.GetResult<Prisma.$PsychologistPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  patient<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the SessionNote model
 */
export interface SessionNoteFieldRefs {
  readonly id: Prisma.FieldRef<"SessionNote", 'Int'>
  readonly sessionId: Prisma.FieldRef<"SessionNote", 'Int'>
  readonly psychologistId: Prisma.FieldRef<"SessionNote", 'Int'>
  readonly patientId: Prisma.FieldRef<"SessionNote", 'Int'>
  readonly subjective: Prisma.FieldRef<"SessionNote", 'String'>
  readonly objective: Prisma.FieldRef<"SessionNote", 'String'>
  readonly assessment: Prisma.FieldRef<"SessionNote", 'String'>
  readonly plan: Prisma.FieldRef<"SessionNote", 'String'>
  readonly riskLevel: Prisma.FieldRef<"SessionNote", 'RiskLevel'>
  readonly createdAt: Prisma.FieldRef<"SessionNote", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"SessionNote", 'DateTime'>
  readonly deletedAt: Prisma.FieldRef<"SessionNote", 'DateTime'>
}
    

// Custom InputTypes
/**
 * SessionNote findUnique
 */
export type SessionNoteFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SessionNote
   */
  select?: Prisma.SessionNoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SessionNote
   */
  omit?: Prisma.SessionNoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SessionNoteInclude<ExtArgs> | null
  /**
   * Filter, which SessionNote to fetch.
   */
  where: Prisma.SessionNoteWhereUniqueInput
}

/**
 * SessionNote findUniqueOrThrow
 */
export type SessionNoteFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SessionNote
   */
  select?: Prisma.SessionNoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SessionNote
   */
  omit?: Prisma.SessionNoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SessionNoteInclude<ExtArgs> | null
  /**
   * Filter, which SessionNote to fetch.
   */
  where: Prisma.SessionNoteWhereUniqueInput
}

/**
 * SessionNote findFirst
 */
export type SessionNoteFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SessionNote
   */
  select?: Prisma.SessionNoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SessionNote
   */
  omit?: Prisma.SessionNoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SessionNoteInclude<ExtArgs> | null
  /**
   * Filter, which SessionNote to fetch.
   */
  where?: Prisma.SessionNoteWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SessionNotes to fetch.
   */
  orderBy?: Prisma.SessionNoteOrderByWithRelationInput | Prisma.SessionNoteOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SessionNotes.
   */
  cursor?: Prisma.SessionNoteWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SessionNotes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SessionNotes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SessionNotes.
   */
  distinct?: Prisma.SessionNoteScalarFieldEnum | Prisma.SessionNoteScalarFieldEnum[]
}

/**
 * SessionNote findFirstOrThrow
 */
export type SessionNoteFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SessionNote
   */
  select?: Prisma.SessionNoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SessionNote
   */
  omit?: Prisma.SessionNoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SessionNoteInclude<ExtArgs> | null
  /**
   * Filter, which SessionNote to fetch.
   */
  where?: Prisma.SessionNoteWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SessionNotes to fetch.
   */
  orderBy?: Prisma.SessionNoteOrderByWithRelationInput | Prisma.SessionNoteOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SessionNotes.
   */
  cursor?: Prisma.SessionNoteWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SessionNotes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SessionNotes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SessionNotes.
   */
  distinct?: Prisma.SessionNoteScalarFieldEnum | Prisma.SessionNoteScalarFieldEnum[]
}

/**
 * SessionNote findMany
 */
export type SessionNoteFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SessionNote
   */
  select?: Prisma.SessionNoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SessionNote
   */
  omit?: Prisma.SessionNoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SessionNoteInclude<ExtArgs> | null
  /**
   * Filter, which SessionNotes to fetch.
   */
  where?: Prisma.SessionNoteWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SessionNotes to fetch.
   */
  orderBy?: Prisma.SessionNoteOrderByWithRelationInput | Prisma.SessionNoteOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing SessionNotes.
   */
  cursor?: Prisma.SessionNoteWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SessionNotes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SessionNotes.
   */
  skip?: number
  distinct?: Prisma.SessionNoteScalarFieldEnum | Prisma.SessionNoteScalarFieldEnum[]
}

/**
 * SessionNote create
 */
export type SessionNoteCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SessionNote
   */
  select?: Prisma.SessionNoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SessionNote
   */
  omit?: Prisma.SessionNoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SessionNoteInclude<ExtArgs> | null
  /**
   * The data needed to create a SessionNote.
   */
  data: Prisma.XOR<Prisma.SessionNoteCreateInput, Prisma.SessionNoteUncheckedCreateInput>
}

/**
 * SessionNote createMany
 */
export type SessionNoteCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many SessionNotes.
   */
  data: Prisma.SessionNoteCreateManyInput | Prisma.SessionNoteCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * SessionNote createManyAndReturn
 */
export type SessionNoteCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SessionNote
   */
  select?: Prisma.SessionNoteSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SessionNote
   */
  omit?: Prisma.SessionNoteOmit<ExtArgs> | null
  /**
   * The data used to create many SessionNotes.
   */
  data: Prisma.SessionNoteCreateManyInput | Prisma.SessionNoteCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SessionNoteIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * SessionNote update
 */
export type SessionNoteUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SessionNote
   */
  select?: Prisma.SessionNoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SessionNote
   */
  omit?: Prisma.SessionNoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SessionNoteInclude<ExtArgs> | null
  /**
   * The data needed to update a SessionNote.
   */
  data: Prisma.XOR<Prisma.SessionNoteUpdateInput, Prisma.SessionNoteUncheckedUpdateInput>
  /**
   * Choose, which SessionNote to update.
   */
  where: Prisma.SessionNoteWhereUniqueInput
}

/**
 * SessionNote updateMany
 */
export type SessionNoteUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update SessionNotes.
   */
  data: Prisma.XOR<Prisma.SessionNoteUpdateManyMutationInput, Prisma.SessionNoteUncheckedUpdateManyInput>
  /**
   * Filter which SessionNotes to update
   */
  where?: Prisma.SessionNoteWhereInput
  /**
   * Limit how many SessionNotes to update.
   */
  limit?: number
}

/**
 * SessionNote updateManyAndReturn
 */
export type SessionNoteUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SessionNote
   */
  select?: Prisma.SessionNoteSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SessionNote
   */
  omit?: Prisma.SessionNoteOmit<ExtArgs> | null
  /**
   * The data used to update SessionNotes.
   */
  data: Prisma.XOR<Prisma.SessionNoteUpdateManyMutationInput, Prisma.SessionNoteUncheckedUpdateManyInput>
  /**
   * Filter which SessionNotes to update
   */
  where?: Prisma.SessionNoteWhereInput
  /**
   * Limit how many SessionNotes to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SessionNoteIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * SessionNote upsert
 */
export type SessionNoteUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SessionNote
   */
  select?: Prisma.SessionNoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SessionNote
   */
  omit?: Prisma.SessionNoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SessionNoteInclude<ExtArgs> | null
  /**
   * The filter to search for the SessionNote to update in case it exists.
   */
  where: Prisma.SessionNoteWhereUniqueInput
  /**
   * In case the SessionNote found by the `where` argument doesn't exist, create a new SessionNote with this data.
   */
  create: Prisma.XOR<Prisma.SessionNoteCreateInput, Prisma.SessionNoteUncheckedCreateInput>
  /**
   * In case the SessionNote was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.SessionNoteUpdateInput, Prisma.SessionNoteUncheckedUpdateInput>
}

/**
 * SessionNote delete
 */
export type SessionNoteDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SessionNote
   */
  select?: Prisma.SessionNoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SessionNote
   */
  omit?: Prisma.SessionNoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SessionNoteInclude<ExtArgs> | null
  /**
   * Filter which SessionNote to delete.
   */
  where: Prisma.SessionNoteWhereUniqueInput
}

/**
 * SessionNote deleteMany
 */
export type SessionNoteDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SessionNotes to delete
   */
  where?: Prisma.SessionNoteWhereInput
  /**
   * Limit how many SessionNotes to delete.
   */
  limit?: number
}

/**
 * SessionNote without action
 */
export type SessionNoteDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SessionNote
   */
  select?: Prisma.SessionNoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SessionNote
   */
  omit?: Prisma.SessionNoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SessionNoteInclude<ExtArgs> | null
}
